# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

version: 0.0.4444 # this will be replaced

environment:
# change here!
  packageVersion: 0.7.6

#nuget publish will fail if not Release
configuration: Release
platform: Any CPU

pull_requests:
  do_not_increment_build_number: true

init:
- ps: $env:IsPrerelease = ($env:APPVEYOR_REPO_TAG -eq $False) -or ($env:APPVEYOR_REPO_BRANCH -ne "master")
- ps: $env:buildVersion = if ($env:IsPrerelease -eq $False) {"$env:packageVersion"} else {"$env:packageVersion.$env:appveyor_build_number"}
- ps: $env:nugetVersion = if ($env:APPVEYOR_REPO_BRANCH -eq "master") {"$env:buildVersion" }  else {"$env:packageVersion-$env:APPVEYOR_REPO_BRANCH$env:appveyor_build_number" }
# send version back
- ps: Update-AppveyorBuild -Version $env:buildVersion
- ps: echo "PreRelease = $env:IsPrerelease"
- ps: echo "BuildVersion = $env:buildVersion"
- ps: echo "nugetVersion = $env:nugetVersion"

# patch all Assemblies to the current build number
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(buildVersion)'
  assembly_file_version: '$(buildVersion)'
  assembly_informational_version: '$(nugetVersion)'

#add custom nuget feed to allow vvvv alpha nugets
install:
- ps: nuget sources add -Name VVVV -Source http://vvvv.org:8111/guestAuth/app/nuget/v1/FeedService.svc/

# having those helps appveyor perf tremendously
cache: 
- src/packages -> **\packages.config
#- '%LocalAppData%\NuGet\Cache'

# untried yet.
nuget:
  project_feed: true

before_build:
- ps: nuget restore src/vvvv-Time.sln -verbosity quiet

build:
  project: src/vvvv-Time.sln
  publish_wap: true
  verbosity: minimal

after_build:
- ps: nuget pack src/core/VVVV.Packs.Time.nuspec -version "$env:nugetVersion"

artifacts:
- path: build/AnyCPU/$(configuration)/
  name: vvvv-Time
  type: WebDeployPackage

- path: build/AnyCPU/$(configuration)/vvvv-Time/core/VVVV.Packs.Timing.dll
  name: dll

- path: '**\VVVV.Packs.Time*.nupkg'
  name: VVVV.Packs.Time
  type: NuGetPackage

deploy:
- provider: GitHub
  draft: true
  description: Automatic Deployment powered by AppVeyor
  auth_token:
    secure: GMMqt9Z8X4poG9NQFBGrbi4hiVnj5Qc1XIWmfl0rdqi8mJevjvECGKRlyIYy07aO
  artifact: vvvv-Time dll
  prerelease: $(IsPrerelease)
  on:
    #allow all branches
    appveyor_repo_tag: true        # deploy on tag push only

- provider: NuGet
  api_key:
    secure: 0hhwaeSEUfUNsjinrtuxpRwIAhwnpo4CdmcVd9nQtxh6kdSLnU1jJkPVRW+sDxkS
  skip_symbols: true
  artifact: VVVV.Packs.Time
  on:
    #alllow all branches
    appveyor_repo_tag: true        # deploy on tag push only